/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : elvis.xu
 * Created : 01/07/2014 04:28:26
 */

package com.xjd.test.fastcode.bean;



public class ModelBBean {

	/* start fields from com.xjd.test.fastcode.ModelB */
	private String name;
	private int age;
	private String address;

	/**
	 *
	 * @return 
	 */
	public String getName() {
		return this.name;
	 }

	/**
	 *
	 * @param name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 *
	 * @return 
	 */
	public int getAge() {
		return this.age;
	 }

	/**
	 *
	 * @param age
	 */
	public void setAge(int age) {
		this.age = age;
	}

	/**
	 *
	 * @return 
	 */
	public String getAddress() {
		return this.address;
	 }

	/**
	 *
	 * @param address
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	
}
